POST http://localhost:3333/events
Content-Type: application/json

{
  "title" : "NLW Unite",
  "details" : "Evento para programadores",
  "maximumAttendees": 100
}

###

POST http://localhost:3333/events/2c060b71-7fa7-418e-9bff-2f2a20075c44/attendees
Content-Type: application/json

{
  "name" : "Thalyson",
  "email" : "thalyson@mail.com"
}

###

GET http://localhost:3333/events/2c060b71-7fa7-418e-9bff-2f2a20075c44
Content-Type: application/json